name: Production Build and Publish
on:
  push:
    branches:
      - main
    paths:
      - '**.py'
      - '**.yml'

jobs:
  buildAndPublish:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout Code
      uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2
      with:
        fetch-depth: ‘2’

    - name: Setup Python
      uses: actions/setup-python@70e2063f710ccef775ec81349f16fb39eecee9ef # v2.2.2
      with:
        python-version: 3.8

    # https://www.peterbe.com/plog/install-python-poetry-github-actions-faster
    - name: Load cached ~/.local
      uses: actions/cache@c64c572235d810460d0d6876e9c705ad5002b353 #v2.1.6
      with:
        path: ~/.local
        key: dotlocal-${{ runner.os }}-${{ hashFiles('.github/workflows/production.yml') }}

    - name: Install poetry
      uses: snok/install-poetry@44d50c1274bf7fe0860f5c0531e36c9092c15b23 # v1.2.1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true

    - name: Build and publish to pypi
      uses: JRubics/poetry-publish@v1.9
      with:
        pypi_token: ${{ secrets.PYPI_TOKEN }}